version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: my-postgres
    environment:
      POSTGRES_USER: timofey
      POSTGRES_PASSWORD: supersecret
      POSTGRES_DB: habrparsedb
    ports:
      - "5555:5555"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
