version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: my-postgres
    env_file:
      - .env
    ports:
      - "5555:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
