version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: my-postgres
    env_file:
      - .env
    ports:
      - "5555:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
  habr_parser:
    build: ./
    container_name: habr_parser
    depends_on:
      - db
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: uvicorn habr_parser.main:app --host 0.0.0.0 --port 8000
    restart: always

volumes:
  pgdata:
