"""Add articles_hubs table

Revision ID: 616136071ce9
Revises: aa032e3235e8
Create Date: 2025-09-16 19:31:24.725099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '616136071ce9'
down_revision: Union[str, Sequence[str], None] = 'aa032e3235e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('articles_hubs',
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('hub_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ),
    sa.ForeignKeyConstraint(['hub_id'], ['hubs.id'], ),
    sa.PrimaryKeyConstraint('article_id', 'hub_id')
    )
    op.create_unique_constraint(None, 'hubs', ['name'])
    op.drop_constraint(op.f('hubs_article_id_fkey'), 'hubs', type_='foreignkey')
    op.drop_column('hubs', 'article_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hubs', sa.Column('article_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('hubs_article_id_fkey'), 'hubs', 'articles', ['article_id'], ['id'])
    op.drop_constraint(None, 'hubs', type_='unique')
    op.drop_table('articles_hubs')
    # ### end Alembic commands ###
